# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        UserBundle\Entity\User: sha256

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class: storeBundle\Entity\User
                property: username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            anonymous: true

        admin:
            pattern: ^/admin
            anonymous: false
            provider: main
            form_login:
                login_path: login
                check_path: /admin/login_check
            logout:
                path: /admin/logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
